apiVersion: v1
kind: Service
metadata:
  name: someone-redis-master
  namespace: someone
  labels:
    app: redis
    role: master
    tier: backend
    associated-app: someone
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
    associated-app: someone

